version: '2'
services:
  spark-master:
    build: ./master
    container_name: spark-master
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:7077:7077
      - 127.0.0.1:6066:6066
    environment:
      - INIT_DAEMON_STEP=setup_spark
    network_mode: "host"
  spark-worker-1:
    build: ./worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 127.0.0.1:8081:8081
    environment:
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_MASTER=spark://your-host:7077"
    network_mode: "host"
  spark-worker-2:
    build: ./worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 127.0.0.1:8082:8082
    environment:
      - "SPARK_WORKER_WEBUI_PORT=8082"
      - "SPARK_MASTER=spark://your-host:7077"
    network_mode: "host"